title:              Ambreth Anish
email:              anish432a@gmail.com
description:        >
  Final year undergraduate student pursuing Mathematics and Computing
  Indian Institute of Technology, Hyderabad
author:             Anish
baseurl:            ""
url:                "https://anish342.github.io"

# Social Profiles
twitter_username:   
github_username: Anish342
facebook_username:  
instagram_username:  
linkedin_username: anish-a-5193b1217

# Add your google-analytics ID here to activate google analytics
google_analytics:    # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
