title:              Anish Ambreth
email:              ambrethanish@gmail.com
description:        >
  Master's Student at MBZUAI | IIT Hyderabad'24
author:             Anish
baseurl:            ""
url:                "https://anish342.github.io"

# Social Profiles
twitter_username:   
github_username: Anish342
facebook_username:  
instagram_username:  
linkedin_username: anish-ambreth-5193b1217

# Add your google-analytics ID here to activate google analytics
google_analytics:  'G-ST298WNNGN'  # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
