remote_theme: "mmistakes/minimal-mistakes@4.26.2"
minimal_mistakes_skin    : "contrast"

locale                   : "en-US"
title                    : "Anish Ambreth"
url                      : "https://anish342.github.io"
repository               : "Anish342/Anish342.github.io"

analytics:
  provider               : "google"
  google:
    tracking_id          : "G-ST298WNNGN"
    anonymize_ip         :

author:
  avatar           : "/assets/images/20251130_103707_Original.jpg"
  # name omitted — hides name under photo
  linkedin         : "anish-ambreth"
  google_scholar   : "citations?user=Zb0Y3VkAAAAJ&hl=en"
  cv               : "/assets/cv/CV.pdf"

include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - package-lock.json
  - Rakefile
  - README
  - tmp
  - /docs
  - /test
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

sass:
  sass_dir: _sass
  style: compressed

permalink: /:categories/:title/
timezone:

paginate: 5
paginate_path: /page:num/

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-titles-from-headings

whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

titles_from_headings:
  enabled:     false
  strip_title: true
  collections: true

compress_html:
  clippings: all
  ignore:
    envs: development

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
      strip_title: true
      read_time: false
      comments: false
      share: false
      related: false
